---
- name: Run the equivalent of "apt-get update" as a separate step
  apt:
    update_cache: yes

- name: Update all packages to the latest version
  apt:
    upgrade: dist

- name: install common packages
  apt:
    name: "{{ item }}"
    state: latest
  with_items:
    - tmux
    - vim